// Export Functions
module.exports.getRandomInteger = require('./Functions/getRandomInteger');
module.exports.tictactoe = require('./Functions/tictactoe');
module.exports.calc = require('./Functions/calculator');
module.exports.rps = require('./Functions/rps');
module.exports.embedPages = require('./Functions/embedPages');
module.exports.num = require('./Functions/number');
module.exports.currency = require('./Functions/currency');
module.exports.sleep = require('./Functions/sleep');
module.exports.choose = require('./Functions/choose');
